apiVersion: v1 
kind: Deployment
metadata:
  name: nginx-web
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec: 
      containers:
        - name: ninx-web-server
          image: nginx
          ports:
            - containerPort: 80
          volumeMount:
            - name: app-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: app-storage
          PersistentVolumeClaim: 
            - claimName: task-pv-claim
      
    