apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mytest-app
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: test
  template:
    metadata:
      labels:
        tier: test
    spec:
      containers:
      - name: mytest-container    
        image: varukoluaravind22/ci-cd:mytestapp-24
        ports:
        - containerPort:  8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5      
      
