apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-web-server
  labels:
    name: webserver
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: varukoluaravind22/devops-docker-images:web-application-1
          ports:
            - containerPort: 80

     
