apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resources
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /upi/ReqPay(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: fin-svc
            port:
              number: 8085
      - path: /upi/ReqListAccount(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: meta-svc
            port:
              number: 8083
      - path: /promtheus
        pathType: Prefix
        backend:
          service:
            name: my-kube-prometheus-stack-operator
            port:
              number: 443
      - path: /alertmanager
        pathType: Prefix
        backend:
          service:
            name: my-kube-prometheus-stack-alertmanager
            port:
              number: 9093     
      