apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resources
spec:
  rules:
  - http:
      paths:
      - path: /upi/ReqPay
        pathType: Prefix
        backend:
          service:
            name: fin-svc
            port:
              number: 8085
      - path: /upi/ReqListAccount
        pathType: Prefix
        backend:
          service:
            name: meta-svc
            port:
              number: 8083