apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-fin-pv
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  nfs:
   server: 192.168.0.117
   path: /home/oracle/oliveissuerfin-data