apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-meta-pv
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  nfs:
    server: 192.168.0.126
    path: /home/k8s/oliveissuermeta-data