apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta-deploy
  labels:
    tier: meta-backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
       tier: meta-backend
  template:
    metadata:
      labels:
        tier: meta-backend
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: oliveissuermeta
        image: varukoluaravind22/podman-images:oliveissuermeta-image-1
        imagePullPolicy: IfNotPresent
        command:
        - java
        args:
        - -Dlog.dir=/upiapp/upinew/oliveissuermeta/log/${POD_NAME}
        - -Dtomcat.dir=upiapp/upinew/oliveissuermeta/tomcat/logs/${POD_NAME}
        - -jar
        - cbi-upi-iss-meta-1.0.0.SNAPSHOT.jar
        ports:
        - containerPort: 8083
        volumeMounts:
        - name: upi-data
          mountPath: /upiapp/upinew/oliveissuermeta/application.properties
          subPath: application.properties
        - name: upi-data
          mountPath: /upiapp/upinew/oliveissuermeta/logback.xml
          subPath: logback.xml
        - name: upi-data
          mountPath: /upiapp/upinew/oliveissuermeta/cfg
          subPath: cfg
        - name: upi-data
          mountPath: /upiapp/upinew/oliveissuermeta/deploy
          subPath: deploy
        - name: log
          mountPath: /upiapp/upinew/oliveissuermeta/log
        - name: logs
          mountPath: /upiapp/upinew/oliveissuermeta/logs
        - name: tomcat 
          mountPath: /upiapp/upinew/oliveissuermeta/tomcat/logs
      volumes:
        - name: upi-data
          persistentVolumeClaim:
            claimName: meta_pvc
        - name: log
          emptydir: {}
        - name: logs
          emptydir: {}
        - name: tomcat
          emptydir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: meta-svc
spec:
  type: ClusterIP
  selector:
    tier: meta-backend
  ports:
  - port: 8083
    