apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fin-pvc
spec:
  storageClassName: manual
  volumeName: nfs-fin-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
