apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: local-pvc
spec:
  storageClassName: manual
  volumeName: nfs-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
