apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meta_pvc
spec:
  storageClassName: manual
  volumeName: nfs-meta-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi