apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
{{ toYaml .Values.deployment.labels | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
{{ toYaml .Values.deployment.labels | nindent 6 }}
  template:
    metadata:
      labels:
{{ toYaml .Values.deployment.labels | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.deployment.image }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ toYaml .Values.service.labels | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
