apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-deploy-food
  nameSpace: prod
  labels:
    tier: food-app
spec: 
  replicas: 1
  selector:
    matchLabels:
      tier: food-app
  template:
    metadata:
      labels:
        tier: food-app
    spec:
      containers:
      - name: food-application
        image: varukoluaravind22/devops-docker-images:food-1
        ports:
        - containerPort: 80
